### ISSUE TITLE
Pressing "p" has almost no effect

### ISSUE THREAD

**Issue by alex-robbins** [htop-dev/htop#1157]
In htop 3.2.1, pressing "p" does not toggle the display of program paths like the help screen says it should. Changing the "Show program paths" setting in the "F2 Setup" screen does work, however.

The weird part is that pressing "p" *does* toggle the setting in the Setup screen, but the behavior around showing program paths doesn't change until you change the setting in the Setup screen (e.g. you toggle it on and then back off).

**Comment by cgzones** [comment]
This is fixed via 1707642f (but not included in any release yet).

**Comment by alex-robbins** [comment]
Oh, cool. Thanks. 

(Looks like the last release was in June? Might be time for another one.)

**Comment by graahnul-grom** [comment]
Still have the same problem.
htop 3.2.2, FreeBSD 13.
Now using 3.2.0, where "p" works as intended.

**Comment by fasterit** [comment]
@BenBE: it works (also on FreeBSD 13.1, htop 3.2.2 from pkg) but there is quite a visible delay on a busy system, so may be this is what users are seeing.
