### ISSUE TITLE
Header layout and meters reset if a header column is empty

### ISSUE THREAD

**Issue by scalisi** [htop-dev/htop#880]
If a header column is empty, the header layout and all meters will reset to the defaults after quitting htop.

Example:

1. Move htoprc and run htop 3.1.2 with default settings.
2. Press F2 and navigate to the meters section.
3. Delete all meters in any column.
4. Quit htop.
5. Run htop and see that the meters have reset to the defaults.

Example 2:

1. Move htoprc and run htop 3.1.2 with default settings.
2. Press F2 and navigate to the header layout section.
3. Select a 3-column layout.
4. Quit htop without adding any meters to the new column.
5. Run htop and see that the header layout has reset to the default.

**Comment by BenBE** [comment]
Please test the following patch which should fix the experienced issue:

```diff
diff --git a/Settings.c b/Settings.c
index 1f13b5a3..21c808e7 100644
--- a/Settings.c
+++ b/Settings.c
@@ -64,14 +64,18 @@ static void Settings_readMeterModes(Settings* this, const char* line, unsigned i
 static bool Settings_validateMeters(Settings* this) {
    const size_t colCount = HeaderLayout_getColumns(this->hLayout);
 
+   bool anyMeter = false;
+
    for (size_t column = 0; column < colCount; column++) {
       char** names = this->hColumns[column].names;
       const int* modes = this->hColumns[column].modes;
       const size_t len = this->hColumns[column].len;
 
-      if (!names || !modes || !len)
+      if (!names || !modes)
          return false;
 
+      anyMeter |= !!len;
+
       // Check for each mode there is an entry with a non-NULL name
       for (size_t meterIdx = 0; meterIdx < len; meterIdx++)
          if (!names[meterIdx])
@@ -81,7 +85,7 @@ static bool Settings_validateMeters(Settings* this) {
          return false;
    }
 
-   return true;
+   return anyMeter;
 }
 
 static void Settings_defaultMeters(Settings* this, unsigned int initialCpuCount) {
```

**Comment by scalisi** [comment]
Hi @BenBE. I applied the patch (https://github.com/scalisi/htop/commit/fd1a67b2a9156c3168d87db964ff6317ee369826), reinstalled htop and deleted my htoprc, but the patch didn't seem to fix the issue for me.

**Comment by cgzones** [comment]
There needs to be a `continue` on an empty length:
```diff
diff --git a/Settings.c b/Settings.c
index 1f13b5a..f4bb060 100644
--- a/Settings.c
+++ b/Settings.c
@@ -64,14 +64,21 @@ static void Settings_readMeterModes(Settings* this, const char* line, unsigned i
 static bool Settings_validateMeters(Settings* this) {
    const size_t colCount = HeaderLayout_getColumns(this->hLayout);
 
+   bool anyMeter = false;
+
    for (size_t column = 0; column < colCount; column++) {
       char** names = this->hColumns[column].names;
       const int* modes = this->hColumns[column].modes;
       const size_t len = this->hColumns[column].len;
 
-      if (!names || !modes || !len)
+      if (!len)
+         continue;
+
+      if (!names || !modes)
          return false;
 
+      anyMeter |= !!len;
+
       // Check for each mode there is an entry with a non-NULL name
       for (size_t meterIdx = 0; meterIdx < len; meterIdx++)
          if (!names[meterIdx])
@@ -81,7 +88,7 @@ static bool Settings_validateMeters(Settings* this) {
          return false;
    }
 
-   return true;
+   return anyMeter;
 }
 
 static void Settings_defaultMeters(Settings* this, unsigned int initialCpuCount) {
```

**Comment by scalisi** [comment]
Hi @cgzones. Adding `continue` on an empty length fixed the issue for me (https://github.com/scalisi/htop/commit/251172a53bccd9d7c2be9ee2da61a5543293d272). Thanks @BenBE and @cgzones.
